start transaction;

create table Links_To_Check
(
	id int primary key generated by default as identity,
	link varchar(256) unique not null
);

-- create unique index Links_To_Check_Index on Links_To_Check(link);

create table Site
(
	id int primary key generated by default as identity,
	link varchar(256) unique not null,
	original_size int not null check(original_size >= 0),
	title varchar(256) not null,
	content text not null,
	creation_date timestamp,
	category varchar(64),
	comment_count int check(comment_count >= 0),
	photo_count int check(photo_count >= 0),
	original_html text
);

-- create unique index Links_Site_Index on Site(link);

create table Controller -- Used to control agents
(
	id int primary key generated by default as identity,
	is_active boolean not null default false,
	is_ready boolean not null default false,
	base_url varchar(256) not null default 'https://www.idnes.cz/'
);

insert into Controller default values;
update Controller set is_ready = true;

commit;